# Generated by Django 4.0.2 on 2022-02-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyproducts',
            name='offeramt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
